### ISSUE TITLE
Frontend Option: MVC (Angular / Ember / Vewe)

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor_app#20]
Epic: #8

This issue exists to discuss the above framework(s).

MVC options:

Pros:
- well-documented
- stable
- very extensible and customizable

Cons:
- Extremely difficult for beginners

**Comment by itsthejoker** [comment]
I've done a fair amount of work in MVC scenarios, but unless we have a really good argument why this is the way to go, I doubt that this is what we should choose. It's deeply unfriendly to beginners, and though it's very powerful when set up correctly, getting it set up is a major pain and could be more trouble than it's worth.

**Comment by DavidArchibald** [comment]
I'd just like to affirm what you've said: I've worked with Angular, and it's incredibly powerful, but the trade off in difficulty isn't worth it, it's quite esoteric looking and almost completely different from normal Javascript. If this pattern I've seen holds up to Ember and Vewe, I really don't see it being good for our purposes, and newer libraries will probably be better.

**Comment by itsthejoker** [comment]
Closing as we have decided this is not the avenue we want to pursue.
